on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.FTP_USERNAME }} 
          server: ${{ secrets.FTP_SERVER }} 
          private_key: ${{ secrets.FTP_KEY }} 
          local_path: './*'
          remote_path: '/opt/bitnami/apps/wordpress/htdocs/' #make sure dir exist
          args: '-o ConnectTimeout=5'
